name: Automation workflow

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install black"
        run: pip install black
      - name: "Run black"
        run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install pytest, matplotlib, coverage, and numpy"
        run: pip install pytest numpy matplotlib coverage
      - name: "Run pytest via coverage"
        run: coverage run -m pytest
      - name: "Show coverage report"
        run: coverage report -m